services:
  - type: web
    name: fyers-fighter
    env: python
    plan: free
    branch: main
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/Home.py --logger.level=error --client.showErrorDetails=false
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: USE_SUPABASE
        value: false
      - key: ENCRYPTION_MASTER_KEY
        sync: false
